### ISSUE TITLE
Should wakaama client tries to register if an update registration fails ?

### ISSUE THREAD

**Issue by kiranpradeep** [eclipse/wakaama#156]
Currently wakaama client updates registration as specified. But if any update registration fails, it doesn't try to re-register. Attaching [logs](https://github.com/eclipse/wakaama/files/286248/tkt.txt)

If wakaama client update registration fails, shouldn't the client try re-registering ? Is this functionality, supposed to added by wakaama library user ?

**Comment by dnav** [comment]
If the a server is not available (registration or update failed), it is ignored to avoid infinte loop of registration.

I need to re-work the behavior in case of failed registration update. For now, a failed registration does not impact the state machine. But the behavior should be the same as a failed registration.
The lib user should indeed inspect the context status and each server status to determine what to do when the lwm2m_step() function returns an error.

**Comment by kiranpradeep** [comment]
Kindly don't get an impression that I am trying to dictate anything. Just telling what I saw with leshan client. Kindly see UpdateRegistrationTask https://github.com/eclipse/leshan/blob/master/leshan-client-core/src/main/java/org/eclipse/leshan/client/servers/RegistrationEngine.java#L264 in leshan client. Here a failed update registration goes all the way to bootstrap server.

**Comment by kiranpradeep** [comment]
Currently a failed bootstrap results in client periodically checking the bootstrap server for valid credentials, until it finds one. But, a failed registration or failed update registration - stops the show. Partiality towards bootstrap :)

**Comment by mlindstedt** [comment]
Sorry, if I misunderstand, but I was investigating why server doesn't respond with a 4.04 to client, when client sends registration update to server. But maybe this is not same problem?

@kiranpradeep, if it is the same problem, then I have a temporary solution for what to change in the Wakamaa implementation.

Because according to specification OMA-TS-LightweightM2M-V1_0-20140619.pdf table 19, then a registration is a POST, but a registration update is a PUT. However PUT doesn't seem to be handled in function registration_handleRequest in core/reservation.c on server-side. So in order to make it work on server-side, I added **case COAP_PUT:** under **case COAP_POST:**:
`
coap_status_t registration_handleRequest(lwm2m_context_t * contextP,
                                          lwm2m_uri_t * uriP,
                                          void * fromSessionH,
                                          coap_packet_t * message,
                                          coap_packet_t * response)
{
    coap_status_t result;
    time_t tv_sec;

    tv_sec = lwm2m_gettime();
    if (tv_sec < 0) return COAP_500_INTERNAL_SERVER_ERROR;

    switch(message->code)
    {
        case COAP_POST:
        case COAP_PUT:
`

and that will trigger line 1042 in the same function:

`
contextP->monitorCallback(clientP->internalID, NULL, COAP_204_CHANGED, LWM2M_CONTENT_TEXT, NULL, 0, contextP->monitorUserData);
`

NOTE: This is just a temporary suggestion on what to change, I'm not a wakamaa expert, so the code might destroy something.

**Comment by boaks** [comment]
Hi Magnus,

> according to specification OMA-TS-LightweightM2M-V1_0-20140619.pdf

There was a change in the COAP method for the registration interface in
the LWM2M TS since that (and there are some more changes in the meantime)
The PUT was replaced by POST to confirm with REST behavior.
There are also discussions about that issue on the OMA issue page.

https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/96


Mit freundlichen Grüßen / Best regards

Achim Kraus

Bosch Software Innovations GmbH
Communications (INST/ESY1)
Stuttgarter Straße 130
71332 Waiblingen
GERMANY
www.bosch-si.de
www.blog.bosch-si.com 

Registered office: Berlin, Register court: Amtsgericht Charlottenburg, HRB 148411 B
Executives: Dr.-Ing. Rainer Kallenbach; Michael Hahn


Von: Magnus Lindstedt [mailto:notifications@github.com] 
Gesendet: Donnerstag, 9. Juni 2016 15:42
An: eclipse/wakaama
Betreff: Re: [eclipse/wakaama] Should wakaama client tries to register if an update registration fails ? (#156)

Sorry, if I misunderstand, but I was investigating why server doesn't respond with a 4.04 to client, when client sends registration update to server. But maybe this is not same problem?
@kiranpradeep, if it is the same problem, then I have a temporary solution for what to change in the Wakamaa implementation.
Because according to specification OMA-TS-LightweightM2M-V1_0-20140619.pdf table 19, then a registration is a POST, but a registration update is a PUT. However PUT doesn't seem to be handled in function registration_handleRequest in core/reservation.c on server-side. So in order to make it work on server-side, I added case COAP_PUT: under case COAP_POST::
`
coap_status_t registration_handleRequest(lwm2m_context_t * contextP,
lwm2m_uri_t * uriP,
void * fromSessionH,
coap_packet_t * message,
coap_packet_t * response)
{
coap_status_t result;
time_t tv_sec;
tv_sec = lwm2m_gettime();
if (tv_sec < 0) return COAP_500_INTERNAL_SERVER_ERROR;

switch(message->code)
{
    case COAP_POST:
    case COAP_PUT:
`
and that will trigger line 1042 in the same function:

contextP->monitorCallback(clientP->internalID, NULL, COAP_204_CHANGED, LWM2M_CONTENT_TEXT, NULL, 0, contextP->monitorUserData);
NOTE: This is just a temporary suggestion on what to change, I'm not a wakamaa expert, so the code might destroy something.

**Comment by mlindstedt** [comment]
Sorry, for having such an old specification. @boaks, you are absolutely correct. After hint from you, I just dowloaded the latest OMA-TS-LightweightM2M-V1_0-20160407-C.pdf, and in chapter 8.2.3 (table 22) it says POST now, not PUT like it did in the old 2014 specification.

The firefox plugin I've been using as LWM2M client (https://addons.mozilla.org/sv-SE/firefox/addon/oma-lwm2m-devkit/) unfortunately support the old way (PUT) though. I will use another LWM2M client in the future, thanks to this new info.

Sorry @kiranpradeep for bothering, I though it was related. I hope you find an answer to your question.

**Comment by jpradocueva** [comment]
Hi Magnus,
Can I kindly ask you to submit an Issue related to this topic in the OMA DevKit GitHub repo?

https://github.com/OpenMobileAlliance/OMA-LWM2M-DevKit/issues

We are collecting issues before release a new version of the tool.

Thank you very much for your support.

Joaquin
---------------------------------------
Director of Technical Programs
Open Mobile Alliance | www.openmobilealliance.org<http://www.openmobilealliance.org>
Cell: (+1) 858 249 8300<tel:%28%2B44%29%20%280%2977%2017%2027%2050%2024>
Skype: (+44) (0) 208 144 7699
Skype/Yahoo: jpradocueva
Email: jprado@omaorg.org<mailto:jprado@omaorg.org>

**Comment by kiranpradeep** [comment]
Thread hijacked. Closed and reopened as issue# 167
