### ISSUE TITLE
Wakaama example client cannot create new instances of custom objects(/1024).

### ISSUE THREAD

**Issue by kiranpradeep** [eclipse/wakaama#230]
I am using lwm2mclient( part of Wakaama examples ) with Leshan device management server hosted at leshan.eclipse.org. I could use "create new instance" button to create new lwm2m object intances for /1( Server) and /2 ( Access Control ) objects. But if I attempt to create new instance of /1024 ([test_object.c](https://github.com/eclipse/wakaama/blob/master/examples/client/test_object.c)), the instance creation fails. [Logs](https://github.com/eclipse/wakaama/files/763218/new_instance.txt) attached.

Code in sync with wakaama/master.
Server: Leshan device management server 0.1.11-M15 ( leshan.eclipse.org )
I am getting same error on different machines with different operating systems and compilers ( with or with out DTLS ).

**Comment by dnav** [comment]
Hi,
This is because Leshan does not know the wakaama test object layout. The create command does not contains values to fill the new instance.
You would need to provide Leshan with the test object layout in the form of a json file. See https://dev.eclipse.org/mhonarc/lists/leshan-dev/msg00211.html

Regards
