### ISSUE TITLE
*** Error in `./lwm2mclient': free(): invalid next size (fast): 0x00516ab0 ***)

### ISSUE THREAD

**Issue by nis267** [eclipse/wakaama#444]
The latest wakaama client crashes with the following error, after clicking on read or observe from the object id /5/0/ (firmware update oject) on the leshan server interface.

*** Error in `./lwm2mclient': free(): invalid next size (fast): 0x00516ab0 ***
Aborted

Can you please fix the issue soon.

Thanks,
Denis

**Comment by sbertin-telular** [comment]
I am getting a memory error serializing with the master branch, but not exactly what you are seeing. I think it is fixed by #435. Can you check if this fixes the issue for you? You can do `git fetch https://github.com/sbertin-telular/wakaama.git resource_instance && git merge --no-commit --no-ff FETCH_HEAD`. `git merge --abort` would then get you back to the unchanged version.

**Comment by sbernard31** [comment]
@nis267 , does the provided tips work for you ? should we close this issue ?

**Comment by sbernard31** [comment]
#435 in integrated in master. So I close this issue.
Feel free to reopen if needed.
