### ISSUE TITLE
Endpointname and DTLS Public identity

### ISSUE THREAD

**Issue by LukasKarel** [eclipse/wakaama#474]
According to 1.0.2 endpointname must be compared with the identifier in the dtls handshake. _"The LwM2M specification defines the use of the endpoint client name in the Bootstrap-Request and in the Register messages.
Since the endpoint client name is not authenticated at the application layer the LwM2M Server MUST compare the received
endpoint client name identifier with the identifier used at the DTLS handshake."_

My questions are:
Do i have to support multiple endpoint names if i am using PSK for encryption? One for each server?
Do i have to use the resource /0/x/3 as endpoint name? Is there anything i am missing?

**Comment by sbernard31** [comment]
I'm not sure this is clearly expressed in the 1.0.x specification, but I understand that the idea is "endpoint name should be unique by device".
The §6.3.1 tries to encourage a format which guarantee uniqueness, this a hint.
And so could be used though several servers.

The specification 1.1.x give more hints about that: 
_"The Endpoint Client Name identifier MUST be unique at the server or servers it is being used with."_  ( see [7.3.1. Endpoint Client Name](http://www.openmobilealliance.org/release/LightweightM2M/V1_1-20180710-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1-20180710-A.html#7-3-1-0-731-Endpoint-Client-Name))

>  Do i have to support multiple endpoint names if i am using PSK for encryption? One for each server?

I would say no. You are using only one endpoint name and you can eventually used different PSK identity but at servers side you should say : "on this server, the device will this endpoint name MUST use this PSK identity" and server should check this.

This is how I understand : 
_"This comparison may either be an equality match or may involve a dedicated lookup table to ensure that LwM2MClients cannot intentionally or due to misconfiguration impersonate other LwM2M Clients._" (source LWM2M 1.0.2 §7.15)

>  Do i have to use the resource /0/x/3 as endpoint name? Is there anything i am missing?

I would say no too. When using PSK, this is for  PSK Identity not the endpoint name.
