### ISSUE TITLE
uriP pointer is used as boolean in uri_toString() in the uri.c file. Line 292 and 338.

### ISSUE THREAD

**Issue by stefanfangvall** [eclipse/wakaama#505]

**Comment by sbertin-telular** [comment]
Line numbers can change. Please refer to a specific commit or show the code in question.

**Comment by sbernard31** [comment]
@stefanfangvall , The ideal is to either use an URL refering to a tag : 

[https://github.com/eclipse/wakaama/blob/**v1.0**/core/uri.c#**L287**](https://github.com/eclipse/wakaama/blob/v1.0/core/uri.c#L287) (In this case the issue was not present in v1.0 so it just for the example)

OR use permanent link : 
![Capture d’écran de 2020-12-08 14-53-54](https://user-images.githubusercontent.com/840294/101492876-90dfd380-3965-11eb-812c-13f9e28a21df.png)

https://github.com/eclipse/wakaama/blob/8784fac655f7baaed3ddc8fa9430655c851bb1f4/core/uri.c#L338

**Comment by sbertin-telular** [comment]
What is the issue? This is a perfectly valid NULL pointer test as it stands.

**Comment by qleisan** [comment]
Wrote a response in #512.

**Comment by qleisan** [comment]
@sbernard31 can we close this?  Part of #513 discussion
