### ISSUE TITLE
Challenges in Interfacing Temperature Sensor

### ISSUE THREAD

**Issue by mini525** [eclipse/wakaama#546]
I am using raspberry pi 4 model. I went through the initial guide and with the help of @qleisan I was able to get the object file for temperature.
 
I found that using linux objects it would be easy to get the sensor data.
1. I have installed the linux drivers in my raspberry pi but during the build these header files are not matching.
2. I copied the include files to the folder and all the header file has linking error? 

I am not sure where to start again? Please suggest.

**Comment by qleisan** [comment]
Hi. It is really difficult to provide help without more information. Can you write the steps you used to install software to your raspberry pi. I could try to replicate what you have done (although it sounds like the problems you face are not really wakaama related).

**Comment by sbertin-telular** [comment]
Also helpful would be what commands you are running and what error messages are you getting.

**Comment by mini525** [comment]
Thanks for getting back, I will provide a detailed steps, 

I am using a dht22 (temperature and humidity) sensor. I found these file dht22.c & dht22.h [link](https://github.com/Filkolev/DHT22-sensor-driver).

[dht22.zip](https://github.com/eclipse/wakaama/files/6067180/dht22.zip)
[dht22_h.zip](https://github.com/eclipse/wakaama/files/6067183/dht22_h.zip)

They have used the linux header files to access the GPIO and IRQ signals (as I understand).

So I imported the files into the ..%wakaama/examples/client folder and modified the Object_Temperature.c

[object_temperature_c.zip](https://github.com/eclipse/wakaama/files/6067196/object_temperature_c.zip)

The first time when I try to compile using cMake ana Make I received an error "linux/hrtimer".

So I googled for commands to install the linux drivers and found this, https://www.raspberrypi.org/documentation/linux/kernel/headers.md

sudo apt install raspberrypi-kernel-headers

![2021-03-02-033138_1920x1080_scrot](https://user-images.githubusercontent.com/76512837/109620495-f1ffe900-7b07-11eb-8ef8-27ee7691d608.png)

After installing the linux drivers I tried to compile the code again. But this time the header files are not identifiable, so I copied the include folder to the client folder of ..wakaama / examples.

Still there was a dependency issues.

Kindly let me know if you need more details on the same.

**Comment by qleisan** [comment]
My advice would be to split the task in two parts (unless you already have done so)
1) follow a guide and get a simple program running that can make use of the sensor
2) integrate the working sensor read program with the wakaama stack

Do you really have to use a kernel driver (things can get very complicated)? When I googled there were user space alternatives, C code and python. [This](https://pimylifeup.com/raspberry-pi-humidity-sensor-dht22/) python tutorial looks promising. If it works you can either move on to test a C program that does the same thing or start working on "integration"

If you get a C program working reading the sensor data integration will probably be more straightforward. If you use python you will have to share sensor data in probably more complex way but since you are on a linux system there are many possibilities.

If you solve 1) and post how you did it, I think I'll be able to help out with 2).

**Comment by rettichschnidi** [comment]
@mini525 Is this still relevant or can it be closed?

**Comment by mini525** [comment]
@rettichschnidi Hi working on it, but slow. Will update my results sooner

**Comment by rettichschnidi** [comment]
I guess this is no longer relevant. Please reopen if I am wrong.
