### ISSUE TITLE
Any new version will be in release plan?

### ISSUE THREAD

**Issue by xuyouming1986** [eclipse/wakaama#670]
We are using wakaama release version 1.0, how ever this version is not recomend by wakaama. Instead, wakaama recomend to use latest master branch code.

But lastest master branch code is not a version, which is not able to be tracked, a release version is needed. So, any release plan? How ever, It's really a long time since last release version~

**Comment by rettichschnidi** [comment]
We do not have any concrete plans for a next release yet, but it would be easy, and, according to @sbernard31, allowed by Eclipse, to add a "snapshot" tag like `snapshot/2022-07-05`.

What do you think? What do @mlasch, @tuve, @qleisan, @sbertin-telular think about this?

**Comment by mlasch** [comment]
Since the initial release, there were a lot of changes and bug fixes. Having something that would reflect this would be great. The use of the `1.0` release should be discouraged. As we are not confident for a next "bigger" release yet, I'm in favor for having a "snapshot" tag targeted for anybody who does not want to use the master branch directly.

**Comment by rettichschnidi** [comment]
I just gave the release workflow of GitHub a try and it seems to produce nicely looking release pages quickly: https://github.com/eclipse/wakaama/releases/tag/snapshots%2F2022-08-03

The release text can still be edited in case need be.

Please note: I did not mark the snapshot as "pre-release" because then it would not replace the 1.0 release on the landing page:
![image](https://user-images.githubusercontent.com/920644/182574002-3ed4f22f-eace-4893-9b9c-4fd602d90ba3.png)

Once we have a (supported, official) release we should mark this one retroactively as pre-release.

Feel free to reopen this issue if you do not like this solution.
