### ISSUE TITLE
How to add a pthread library in the build

### ISSUE THREAD

**Issue by dgooris** [eclipse/wakaama#672]
Team,

Nor so much an issue really, but more a request for help:

In my wakaama build I add various functions, and one of them is using pthread and sqlite3.
I added the following in the wakaama.cmake:

add_link_options(
    -lpthread
    -lm
    -lsqlite3
)

This is accepted, though the final CMakeFiles/lwm2mclient_tinydtls.dir/link.txt which contains the actual compile arguments shows that the libraries are at the start of the cc, see this excerpt: 

==> link.txt <==
/usr/bin/cc   -lpthread -lm -lsqlite3 CMakeFiles/lwm2mclient_tinydtls.dir/lwm2mclient.c.o ....

This result in missing functions in pthread etc.

If I edit the link.txt and move the -lpthread -lm -lsqlite3 to the end of the command, I have a perfect build.

What can I do to have these libraries always at the end in the compile command ?
Where in the wakaama.cmake, or other input file can I control this ?

Many thanks,   - Dirk Gooris

**Comment by boaks** [comment]
FMPOV, that's a question for the cmake forum or help.

[add_link_options](https://cmake.org/cmake/help/latest/command/add_link_options.html)

###################################################

Add options to the link step for executable, shared library or module library targets in the current directory and below that are added after this command is invoked.

add_link_options(<option> ...)

This command can be used to add any link options, but alternative commands exist to add libraries ([target_link_libraries()](https://cmake.org/cmake/help/latest/command/target_link_libraries.html#command:target_link_libraries) or [link_libraries()](https://cmake.org/cmake/help/latest/command/link_libraries.html#command:link_libraries)). See documentation of the [directory](https://cmake.org/cmake/help/latest/prop_dir/LINK_OPTIONS.html#prop_dir:LINK_OPTIONS) and [target](https://cmake.org/cmake/help/latest/prop_tgt/LINK_OPTIONS.html#prop_tgt:LINK_OPTIONS) LINK_OPTIONS properties.

###################################################

So, try to use `target_link_libraries` instead.
(But I hove not verified, that it works ;-), I leave that to you.)

**Comment by dirkgooris** [comment]
Thanks for these directions. It tried this:

I updated this file :   `examples/client/CMakeLists.txt  with target_link_options()` in the next lines:

```
    add_executable(lwm2mclient_tinydtls ${SOURCES})

    set_target_properties(lwm2mclient_tinydtls PROPERTIES DTLS "tinydtls")
    target_compile_definitions(lwm2mclient_tinydtls PRIVATE LWM2M_CLIENT_MODE LWM2M_BOOTSTRAP LWM2M_SUPPORT_SENML_JSON)
    target_sources_wakaama(lwm2mclient_tinydtls)
    target_sources_shared(lwm2mclient_tinydtls)

    target_link_options(lwm2mclient_tinydtls PRIVATE LINKER:-lpthread -lm -lsqlite3)
```

This will also generate a faulty cc command.  See the very top of the link.txt file:

`CMakeFiles/lwm2mclient_tinydtls.dir/link.txt`

`/usr/bin/cc -Wl,  **-lpthread -lm -lsqlite3**  CMakeFiles/lwm2mclient_tinydtls.dir/lwm2mclient.c.o  <other .o files>`

And this build results in missing libraries of pthread and sqlite3, because the -l options are not take at the start of the cc.

Again, if I move the `-lpthread -lm -lsqlite3` to the end of the link.txt and run this as a copy/paste, it compiles without any error.

I am not sure its a cmake issue really. The previous versions of Wakaama accepted this command in the same CMakeLists.txt:

`   TARGET_LINK_LIBRARIES(lwm2mclient pthread m sqlite3)`

The result of that function/macro resulted in the right syntax of cc, see the libraries at the end of the cc command:

`   /usr/bin/cc     CMakeFiles/lwm2mclient.dir/lwm2mclient.c.o <and all the other .o's>  -o lwm2mclient -rdynamic -lpthread -lm -lsqlite3`

In general terms to build Wakaama against an application; what would be the preferred way to link these type of libraries otherwise ?  Or should I open a question to cmake how to control the position of the libraries when using  target_link_options() ?

Many thanks again, regards.

**Comment by dirkgooris** [comment]
Good news,

I mixed up the use of target_link_options() with the suggested target_link_libraries()  by Achim Kraus. 
It works now. Here are the changes I made in `examples/client/CMakeLists.txt`

```
# Client without DTLS support
add_executable(lwm2mclient ${SOURCES})
target_compile_definitions(lwm2mclient PRIVATE LWM2M_CLIENT_MODE LWM2M_BOOTSTRAP LWM2M_SUPPORT_SENML_JSON)
target_sources_wakaama(lwm2mclient)
target_sources_shared(lwm2mclient)

# Add the libraries that our application uses
target_link_libraries(lwm2mclient pthread m sqlite3)

# Client with DTLS support provided by tinydtls
add_executable(lwm2mclient_tinydtls ${SOURCES})

set_target_properties(lwm2mclient_tinydtls PROPERTIES DTLS "tinydtls")
target_compile_definitions(lwm2mclient_tinydtls PRIVATE LWM2M_CLIENT_MODE LWM2M_BOOTSTRAP LWM2M_SUPPORT_SENML_JSON)
target_sources_wakaama(lwm2mclient_tinydtls)
target_sources_shared(lwm2mclient_tinydtls)

# Add the libraries that our application uses
target_link_libraries(lwm2mclient_tinydtls pthread m sqlite3)
```

Question answered and problem solved - thanks Achim :-)

Regards, - Dirk Gooris

**Comment by boaks** [comment]
If it's solved, please close the issue.
