### ISSUE TITLE
CBOR encoding, any plan for support?

### ISSUE THREAD

**Issue by ramadhanafif** [eclipse/wakaama#699]
Hi, does anyone know if wakaama has plan for CBOR?

If not, can anyone points out to CBOR standards that LWM2M accepts?

**Comment by mlasch** [comment]
Hello @ramadhanafif,

there is something in the pipeline to support CBOR. We already use `senml-cbor` internally which is based on work from @sbertin-telular and @broglep-work. For now the focus is on server support without having tested the client, since we use the client implementation of [Zephyr](https://www.zephyrproject.org/).

It should be compatible with lwm2m 1.1 though.

I quickly rebased the code on the current `master` here: https://github.com/husqvarnagroup/wakaama/tree/gardena/feature-senml-cbor. This should still be regarded as WIP, as it needs some fixes with recent changes in the CI pipeline.

**Comment by ramadhanafif** [comment]
Thanks for the response @mlasch . I was looking for encoding that denser than json and senml_json. 

So far TLV has been working nicely but I was wondering whether CBOR would be even better.

**Comment by mlasch** [comment]
`senml_cbor` defined in LwM2M 1.1 is denser than JSON and senml_json, but not as dense as TLV. But AFAIK TLV is not recommended/supported in lwm2m 1.1. E.g. the send operation is not possible with TLV.

lwm2m 1.2 offers a new denser LwM2M CBOR coding, however Wakaama does not even partially support LwM2M 1.2.

**Comment by ramadhanafif** [comment]
@mlasch Thanks for your insights on TLV, appreciate that.


Also
> I quickly rebased the code on the current master here: https://github.com/husqvarnagroup/wakaama/tree/gardena/feature-senml-cbor. This should still be regarded as WIP, as it needs some fixes with recent changes in the CI pipeline.

Would you say that the `senml_cbor` in wakaama is ready?

**Comment by mlasch** [comment]
> Would you say that the `senml_cbor` in wakaama is ready?

I would say so, yes. I can only speak about the server side, though. I haven't tested the implementation with the client code yet.

We use the `senml_cbor` encoding already internally. I just started some effort to upstream our code. It needs some adjustments to comply with the current compiler warnings and errors.

**Comment by ramadhanafif** [comment]
Nice to hear that. Do you need additional hands?
