### ISSUE TITLE
SonarCloud and CodeQL jobs failed

### ISSUE THREAD

**Issue by parmi93** [eclipse/wakaama#721]
Every time I send a PR I immediately receive these two emails
What does this mean and how can I fix this?

![image](https://github.com/eclipse/wakaama/assets/61920513/6628257a-fe8d-4664-9552-1a160e544ea0)
![image](https://github.com/eclipse/wakaama/assets/61920513/fa0188f5-d5ef-4f4a-ab2e-49e6b18877db)

**Comment by mlasch** [comment]
The Wakaama build/test pipeline uses SonarCloud and CodeQL to (statically) analyze the code. It seems that our CodeQL task is outdated and should be updated. It will look into this. For SonarCloud, I think you need an account and add it to your Github as a integration in order to have it run successfully.
